name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend  # All commands will run in backend directory

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Update to match your required PHP version
        extensions: sqlite, mbstring, ctype, xml, tokenizer, json, dom  # Add required extensions
        coverage: none

    - name: Copy .env
      run: |
        cp -n .env.example .env || true

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Generate application key
      run: php artisan key:generate

    - name: Create SQLite database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Set permissions
      run: |
        chmod -R 777 storage bootstrap/cache

    - name: Run tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
