name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Navigate to backend directory
      run: |
        echo "Current directory: $(pwd)"
        ls -la
        cd backend
        echo "Backend directory: $(pwd)"
        ls -la

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Update to match your required PHP version
        extensions: sqlite, mbstring, ctype, xml, tokenizer, json, dom  # Add required extensions
        coverage: none

    - name: Copy .env.example to .env
      run: |
        if [ -f .env.example ]; then
          cp .env.example .env
        else
          echo ".env.example not found!"
          exit 1
        fi

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Generate application key
      run: php artisan key:generate

    - name: Create SQLite database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Set permissions
      run: |
        chmod -R 777 storage bootstrap/cache

    - name: Run tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
