name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, json, libxml, zip
        
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Update Database Path in .env
      run: |
        sed -i "s|DB_CONNECTION=.*|DB_CONNECTION=sqlite|g" .env
        sed -i "s|DB_DATABASE=.*|DB_DATABASE=${{ github.workspace }}/back/database/database.sqlite|g" .env

    - name: Create Database Directory
      run: |
        mkdir -p database
        touch database/database.sqlite
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run Database Migrations
      run: php artisan migrate --force --seed

    - name: Run Tests
      run: php artisan test
